wget https://openweathermap.org/img/wn/00d.png
wget https://openweathermap.org/img/wn/00n.png
wget https://openweathermap.org/img/wn/01d.png
wget https://openweathermap.org/img/wn/01n.png
wget https://openweathermap.org/img/wn/02d.png
wget https://openweathermap.org/img/wn/02n.png
wget https://openweathermap.org/img/wn/03d.png
wget https://openweathermap.org/img/wn/03n.png
wget https://openweathermap.org/img/wn/04d.png
wget https://openweathermap.org/img/wn/04n.png
wget https://openweathermap.org/img/wn/05d.png
wget https://openweathermap.org/img/wn/05n.png
wget https://openweathermap.org/img/wn/06d.png
wget https://openweathermap.org/img/wn/06n.png
wget https://openweathermap.org/img/wn/07d.png
wget https://openweathermap.org/img/wn/07n.png
wget https://openweathermap.org/img/wn/08d.png
wget https://openweathermap.org/img/wn/08n.png
wget https://openweathermap.org/img/wn/09d.png
wget https://openweathermap.org/img/wn/09n.png
wget https://openweathermap.org/img/wn/10d.png
wget https://openweathermap.org/img/wn/10n.png
wget https://openweathermap.org/img/wn/11d.png
wget https://openweathermap.org/img/wn/11n.png
wget https://openweathermap.org/img/wn/12d.png
wget https://openweathermap.org/img/wn/12n.png
wget https://openweathermap.org/img/wn/13d.png
wget https://openweathermap.org/img/wn/13n.png
wget https://openweathermap.org/img/wn/14d.png
wget https://openweathermap.org/img/wn/14n.png
wget https://openweathermap.org/img/wn/15d.png
wget https://openweathermap.org/img/wn/15n.png
wget https://openweathermap.org/img/wn/16d.png
wget https://openweathermap.org/img/wn/16n.png
wget https://openweathermap.org/img/wn/17d.png
wget https://openweathermap.org/img/wn/17n.png
wget https://openweathermap.org/img/wn/18d.png
wget https://openweathermap.org/img/wn/18n.png
wget https://openweathermap.org/img/wn/19d.png
wget https://openweathermap.org/img/wn/19n.png
wget https://openweathermap.org/img/wn/20d.png
wget https://openweathermap.org/img/wn/20n.png
wget https://openweathermap.org/img/wn/21d.png
wget https://openweathermap.org/img/wn/21n.png
wget https://openweathermap.org/img/wn/22d.png
wget https://openweathermap.org/img/wn/22n.png
wget https://openweathermap.org/img/wn/23d.png
wget https://openweathermap.org/img/wn/23n.png
wget https://openweathermap.org/img/wn/24d.png
wget https://openweathermap.org/img/wn/24n.png
wget https://openweathermap.org/img/wn/25d.png
wget https://openweathermap.org/img/wn/25n.png
wget https://openweathermap.org/img/wn/26d.png
wget https://openweathermap.org/img/wn/26n.png
wget https://openweathermap.org/img/wn/27d.png
wget https://openweathermap.org/img/wn/27n.png
wget https://openweathermap.org/img/wn/28d.png
wget https://openweathermap.org/img/wn/28n.png
wget https://openweathermap.org/img/wn/29d.png
wget https://openweathermap.org/img/wn/29n.png
wget https://openweathermap.org/img/wn/30d.png
wget https://openweathermap.org/img/wn/30n.png
wget https://openweathermap.org/img/wn/31d.png
wget https://openweathermap.org/img/wn/31n.png
wget https://openweathermap.org/img/wn/32d.png
wget https://openweathermap.org/img/wn/32n.png
wget https://openweathermap.org/img/wn/33d.png
wget https://openweathermap.org/img/wn/33n.png
wget https://openweathermap.org/img/wn/34d.png
wget https://openweathermap.org/img/wn/34n.png
wget https://openweathermap.org/img/wn/35d.png
wget https://openweathermap.org/img/wn/35n.png
wget https://openweathermap.org/img/wn/36d.png
wget https://openweathermap.org/img/wn/36n.png
wget https://openweathermap.org/img/wn/37d.png
wget https://openweathermap.org/img/wn/37n.png
wget https://openweathermap.org/img/wn/38d.png
wget https://openweathermap.org/img/wn/38n.png
wget https://openweathermap.org/img/wn/39d.png
wget https://openweathermap.org/img/wn/39n.png
wget https://openweathermap.org/img/wn/40d.png
wget https://openweathermap.org/img/wn/40n.png
wget https://openweathermap.org/img/wn/41d.png
wget https://openweathermap.org/img/wn/41n.png
wget https://openweathermap.org/img/wn/42d.png
wget https://openweathermap.org/img/wn/42n.png
wget https://openweathermap.org/img/wn/43d.png
wget https://openweathermap.org/img/wn/43n.png
wget https://openweathermap.org/img/wn/44d.png
wget https://openweathermap.org/img/wn/44n.png
wget https://openweathermap.org/img/wn/45d.png
wget https://openweathermap.org/img/wn/45n.png
wget https://openweathermap.org/img/wn/46d.png
wget https://openweathermap.org/img/wn/46n.png
wget https://openweathermap.org/img/wn/47d.png
wget https://openweathermap.org/img/wn/47n.png
wget https://openweathermap.org/img/wn/48d.png
wget https://openweathermap.org/img/wn/48n.png
wget https://openweathermap.org/img/wn/49d.png
wget https://openweathermap.org/img/wn/49n.png
wget https://openweathermap.org/img/wn/50d.png
wget https://openweathermap.org/img/wn/50n.png
